name: Check config
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dnscontrol
        run: |
          brew update
          brew install dnscontrol
      - name: Run dnscontrol check
        run: ls -a